name: 'AWS Update S3 Action'
description: 'Update S3 Bucket in AWS'
author: 'Kyle Calica'
branding:
  icon: 'check-square'
  color: 'orange'
inputs:
  bucket:
    description: 'Bucket Name'
    default: ''
  package:
    description: 'Package to upload S3'
    default: ''
  key:
    description: 'Key'
    default: ''
  AWS_SECRET_KEY:
    description: 'AWS Secret Key'
    default: ''
  AWS_SECRET_ID:
    description: 'AWS Secret Key'
    default: ''
  AWS_REGION:
    description: 'AWS Region'
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
